Question 1:
Create a 2D NumPy array with dimensions 5x5. Replace all elements in the last column with the mean value of that column.

import numpy as np

In [1]:
import numpy as np

array = np.random.randint(1, 10, size=(5, 5))
print("Original Array:")
print(array)

last_column_mean = np.mean(array[:, -1])
array[:, -1] = last_column_mean

print("\nArray After Replacing Last Column with Mean Value:")
print(array)


Original Array:
[[3 6 1 6 9]
 [2 7 7 3 1]
 [9 4 9 4 1]
 [7 5 5 5 7]
 [1 2 3 7 8]]

Array After Replacing Last Column with Mean Value:
[[3 6 1 6 5]
 [2 7 7 3 5]
 [9 4 9 4 5]
 [7 5 5 5 5]
 [1 2 3 7 5]]


Question 2
Create a NumPy array with the numbers 1 to 100. Reshape it into a 10x10 array. Calculate the sum of each row and find the row with the maximum sum.(Hint: you can use 'np.random.randint' to create the 2d array and fill it with random numbers.

import numpy as np

In [3]:
import numpy as np

array_1d = np.arange(1, 101)

array_2d = array_1d.reshape((10, 10))

row_sums = np.sum(array_2d, axis=1)

max_sum_row_index = np.argmax(row_sums)

print("10x10 Array:")
print(array_2d)
print("\nSum of each row:")
print(row_sums)
print(f"\nRow with the maximum sum (index {max_sum_row_index}):")
print(array_2d[max_sum_row_index])



10x10 Array:
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

Sum of each row:
[ 55 155 255 355 455 555 655 755 855 955]

Row with the maximum sum (index 9):
[ 91  92  93  94  95  96  97  98  99 100]
